const products = [
  { name: 'Prawns 10/12 pcs', basePrice: 1000, image: 'images/prawns1.jpg' },
  { name: 'Prawns 15/18 pcs', basePrice: 850, image: 'images/prawns4.jpg' },
  { name: 'Prawns 25/30 pcs', basePrice: 700, image: 'images/prawns3.jpg' },
  { name: 'Prawns 35/40 pcs', basePrice: 600, image: 'images/prawns.jpg' },
  { name: 'Prawns 50/55 pcs', basePrice: 550, image: 'images/prawns2.jpg' },
  { name: 'Pomfret 4/5 pcs', basePrice: 1200, image: 'images/pomfret3.jpg' },
  { name: 'Pomfret 3 pcs', basePrice: 1300, image: 'images/pomfret1.jpg' },
  { name: 'Pomfret 2 pcs', basePrice: 1600, image: 'images/pomfret2.jpg' },
  { name: 'Surmai Small', basePrice: 700, image: 'images/surma1.jpg' },
  { name: 'Surmai Big', basePrice: 900, image: 'images/surma2.jpg' },
  { name: 'Surmai Fillet Boneless', basePrice: 1500, image: 'images/surma2.jpg' },
  { name: 'Rawas Slices', basePrice: 800, image: 'images/rawas1.jpg' },
  { name: 'Rawas Fillet Boneless', basePrice: 1600, image: 'images/rawas2.jpg' },
  { name: 'Halwa Slices', basePrice: 800, image: 'images/halwa1.jpg' },
  { name: 'Hamoor Slices', basePrice: 700, image: 'images/hamoor1.jpg' },
  { name: 'Dara Slices', basePrice: 800, image: 'images/dara1.jpg' },
  { name: 'Dara Fillet Boneless', basePrice: 1600, image: 'images/dara2.jpg' },
  { name: 'Sea Bass Slices', basePrice: 700, image: 'images/seabass1.jpg' },
  { name: 'Sea Bass Fillet Boneless', basePrice: 1500, image: 'images/seabass2.jpg' },
  { name: 'Red Snapper Slices', basePrice: 700, image: 'images/red snapper1.jpg' },
  { name: 'Red Snapper Fillet Boneless', basePrice: 1400, image: 'images/red snapper2.jpg' },
  { name: 'Koti Fillet Boneless', basePrice: 1000, image: 'images/koti.jpg' },
  { name: 'Mahi-Mahi Slices', basePrice: 400, image: 'images/mahimahi1.jpg' },
  { name: 'Mahi-Mahi Fillet Boneless', basePrice: 700, image: 'images/mahimahi2.jpg' },
  { name: 'Ghol Fish Slices', basePrice: 700, image: 'images/surma2.jpg' },
  { name: 'Ghol Fish Fillet Boneless', basePrice: 1400, image: 'images/surma2.jpg' },
  { name: 'Tuna Slices', basePrice: 450, image: 'images/surma2.jpg' },
  { name: 'Tuna Fillet', basePrice: 850, image: 'images/surma2.jpg' },
  { name: 'Bombil (Bombay Duck)', basePrice: 350, image: 'images/surma2.jpg' },
  { name: 'Mackerel (Bangda)', basePrice: 350, image: 'images/surma2.jpg' },
  { name: 'Squid', basePrice: 500, image: 'images/squid.jpg' },
  { name: 'Lobster 1 piece', basePrice: 2600, image: 'images/lobster.jpg' },
  { name: 'Lobster 2 pcs', basePrice: 2400, image: 'images/lobster2.jpg' },
  { name: 'Lobster 3 pcs', basePrice: 1900, image: 'images/lobster3.jpg' },
  { name: 'Lobster 4 pcs', basePrice: 1400, image: 'images/lobster4.jpg' },
  { name: 'Crab 3-4 medium', basePrice: 900, image: 'images/crab.jpg' },
  { name: 'Crab 2 large', basePrice: 1300, image: 'images/crab2.jpg' },
  { name: 'Crab 1 XL', basePrice: 2000, image: 'images/crab4.jpg' },
];
