const products = [
  { name: 'Prawns 10/12 pcs', basePrice: 1000, image: 'images/default.jpg' },
  { name: 'Prawns 15/18 pcs', basePrice: 850, image: 'images/default.jpg' },
  { name: 'Prawns 25/30 pcs', basePrice: 700, image: 'images/default.jpg' },
  { name: 'Prawns 35/40 pcs', basePrice: 600, image: 'images/default.jpg' },
  { name: 'Prawns 50/55 pcs', basePrice: 550, image: 'images/default.jpg' },
  { name: 'Pomfret 4/5 pcs', basePrice: 1200, image: 'images/default.jpg' },
  { name: 'Pomfret 3 pcs', basePrice: 1300, image: 'images/default.jpg' },
  { name: 'Pomfret 2 pcs', basePrice: 1600, image: 'images/default.jpg' },
  { name: 'Surmai Small', basePrice: 700, image: 'images/default.jpg' },
  { name: 'Surmai Big', basePrice: 900, image: 'images/default.jpg' },
  { name: 'Surmai Fillet Boneless', basePrice: 1500, image: 'images/default.jpg' },
  { name: 'Rawas Slices', basePrice: 800, image: 'images/default.jpg' },
  { name: 'Rawas Fillet Boneless', basePrice: 1600, image: 'images/default.jpg' },
  { name: 'Halwa Slices', basePrice: 800, image: 'images/default.jpg' },
  { name: 'Hamoor Slices', basePrice: 700, image: 'images/default.jpg' },
  { name: 'Dara Slices', basePrice: 800, image: 'images/default.jpg' },
  { name: 'Dara Fillet Boneless', basePrice: 1600, image: 'images/default.jpg' },
  { name: 'Sea Bass Slices', basePrice: 700, image: 'images/default.jpg' },
  { name: 'Sea Bass Fillet Boneless', basePrice: 1500, image: 'images/default.jpg' },
  { name: 'Red Snapper Slices', basePrice: 700, image: 'images/default.jpg' },
  { name: 'Red Snapper Fillet Boneless', basePrice: 1400, image: 'images/default.jpg' },
  { name: 'Koti Fillet Boneless', basePrice: 1000, image: 'images/default.jpg' },
  { name: 'Mahi-Mahi Slices', basePrice: 400, image: 'images/default.jpg' },
  { name: 'Mahi-Mahi Fillet Boneless', basePrice: 700, image: 'images/default.jpg' },
  { name: 'Ghol Fish Slices', basePrice: 700, image: 'images/default.jpg' },
  { name: 'Ghol Fish Fillet Boneless', basePrice: 1400, image: 'images/default.jpg' },
  { name: 'Tuna Slices', basePrice: 450, image: 'images/default.jpg' },
  { name: 'Tuna Fillet', basePrice: 850, image: 'images/default.jpg' },
  { name: 'Bombil (Bombay Duck)', basePrice: 350, image: 'images/default.jpg' },
  { name: 'Mackerel (Bangda)', basePrice: 350, image: 'images/default.jpg' },
  { name: 'Squid', basePrice: 500, image: 'images/default.jpg' },
  { name: 'Lobster 1 piece', basePrice: 2600, image: 'images/default.jpg' },
  { name: 'Lobster 2 pcs', basePrice: 2400, image: 'images/default.jpg' },
  { name: 'Lobster 3 pcs', basePrice: 1900, image: 'images/default.jpg' },
  { name: 'Lobster 4 pcs', basePrice: 1400, image: 'images/default.jpg' },
  { name: 'Crab 3-4 medium', basePrice: 900, image: 'images/default.jpg' },
  { name: 'Crab 2 large', basePrice: 1300, image: 'images/default.jpg' },
  { name: 'Crab 1 XL', basePrice: 2000, image: 'images/default.jpg' },
];
